Add email_validate to check mqm.

diff --git a/hub/email_validate b/hub/email_validate
--- a/hub/email_validate
+++ b/hub/email_validate
@@ -103,6 +103,19 @@ function query_email_logs_in_job_jboss {
     fi
 }
 
+function check_mqm_queue {
+    . /nas/home/minjzhang/bin/base
+
+    $BIN/purge_mqm -e $envid -l > /dev/null
+    rc=$?
+
+    if [[ "$rc" == 0 ]]; then
+        echo "Check no MQM pending messages:                            PASS"
+    else
+        echo "Check no MQM pending messages:                            FAIL"
+    fi
+}
+
 #
 # Check network settings for mqm/mqs, including subnet mask
 #
@@ -161,6 +174,7 @@ function check_mail_dir_new {
 #
 
 check_mqm_ifconfig
+check_mqm_queue
 check_mri_passwd
 check_mail_dir_new
 if [[ "$email_address" != "" ]]; then
